### ISSUE TITLE
Update to be compatible with React ^15.5

### ISSUE THREAD

**Issue by dananichev** [react-component/align#13]
15.5 show deprecation warning. 16.x will not support ``React.PropTypes`` and ``React.createClass()``.

I will submit PR a little bit later.

**Comment by dananichev** [comment]
Nvm. You already fixed those warnings.

**Comment by JonnyBurger** [comment]
Can you publish a version with these changes to npm?

**Comment by yesmeck** [comment]
Already published.

**Comment by JonnyBurger** [comment]
@yesmeck You're right, it was because of my lockfile. Sorry.
