### ISSUE TITLE
findDOMNode was called on an unmounted component.

### ISSUE THREAD

**Issue by tyruk** [react-component/align#7]
Due to debounce mechanism (function buffer), the forceAlign method may be triggered even after component was removed from DOM tree. This will result in findDOMNode was called on an unmounted component error.

The easy fix is to check if component is mounted, something like

    forceAlign() {
        const props = this.props;
        if (!props.disabled && ReactDOM.isMounted(this)) {
            const source = ReactDOM.findDOMNode(this);
            props.onAlign(source, align(source, props.target(), props.align));
        }
    },

but since isMounted method is deprecated, this isn't probably a best solution

**Comment by Tlapi** [comment]
+1

**Comment by Tlapi** [comment]
@yiminghe What do you think?

**Comment by yiminghe** [comment]
thanks.
