### ISSUE TITLE
IE11 throws TypeError: Object doesn't support property or method 'contains'

### ISSUE THREAD

**Issue by zachguo** [react-component/align#75]
rc-align v4.0.3
antd v4.4.3
https://github.com/react-component/align/blob/dbe24660c66c6b17049f56cc41e5985ced6e56f5/src/util.ts#L36

**Comment by patrickomeara** [comment]
This issue is holding our upgrade up as well. Looking forward to getting the PR merged.

**Comment by zachguo** [comment]
We temporarily work around this by replacing the `document.contains` string with `document.body.contains` using a webpack loader.

```
  module: {
    rules: [
      ...,
      // replace 'document.contains' with 'document.body.contains' for IE compatibility, util rc-align fixes it
      {
        test: /\.js$/,
        include: [path.resolve(__dirname, "node_modules/rc-align")],
        loader: "string-replace-loader",
        options: {
          search: "document.contains(",
          replace: "document.body.contains("
        }
      }
    ]
  }
```

**Comment by patrickomeara** [comment]
Ah, thanks @zachguo that's great info. Hopefully the fix isn't too far away.

**Comment by pig800509** [comment]
+1,  waiting.....
